n1 = input('Digite algo: ')
print('isalpha: ', n1.isalpha())
print('isnumeric: ', n1.isnumeric())
print('isalnum: ', n1.isalnum())
print('isupper: ', n1.isupper())
print('isascii: ', n1.isascii())
print('isdigit: ', n1.isdigit())
print('isdecimal: ', n1.isdecimal())
print('isidentifier: ', n1.isidentifier())
print('islower: ', n1.islower())
print('isprintable: ', n1.isprintable())
print('isspace: ', n1.isspace())
print('istitle: ', n1.istitle())
print(n1.__init_subclass__())

